import { Platform } from 'react-native';

export const stitchTheme = {
  fonts: {
    body: Platform.select({ ios: 'Inter', android: 'Inter', default: 'Inter' }),
    heading: Platform.select({ ios: 'Inter', android: 'Inter', default: 'Inter' }),
    display: Platform.select({ ios: 'Inter', android: 'Inter', default: 'Inter' }),
    label: Platform.select({ ios: 'Inter', android: 'Inter', default: 'Inter' }),
  },
  colors: {
    background: '#f5f0e8',
    backgroundAccent: '#fdfaf4',
    backgroundElevated: '#f8f3ec',
    surface: '#fdfaf4',
    surfaceMuted: '#efe5d6',
    surfaceSubtle: '#f8f3ec',
    surfaceRaised: 'rgba(253,250,244,0.96)',
    surfaceSoft: '#eef5ff',
    surfaceTint: '#d8f3e4',
    surfaceGhost: 'rgba(253,250,244,0.86)',
    text: '#1a1a18',
    textMuted: '#8a9280',
    textSoft: '#4a5240',
    primary: '#1a3d2b',
    primaryContainer: '#2d6a4f',
    primaryGradientStart: '#112a1e',
    primaryGradientEnd: '#2d6a4f',
    primarySoft: '#b7e4c7',
    primaryDim: '#52b788',
    accentBlue: '#2f63ea',
    accentBlueSoft: '#d0eaff',
    accentRed: '#b7101d',
    accentPeach: '#fde8c8',
    accentBrown: '#c97d2e',
    border: '#e4d9c5',
    line: '#e4d9c5',
    borderStrong: '#d9ccb7',
    chip: '#f0e7da',
    chipActive: '#d8f3e4',
    successSurface: '#d8f3e4',
    warningSurface: '#fde8c8',
    dangerSurface: '#f7e3e4',
    shadow: 'rgba(26,61,43,0.10)',
    shadowStrong: 'rgba(26,61,43,0.16)',
    forestDeep: '#112a1e',
    mintLight: '#d8f3e4',
    sand: '#e4d9c5',
    warmWhite: '#fdfaf4',
  },
  radius: {
    xs: 10,
    sm: 14,
    md: 16,
    card: 20,
    lg: 22,
    xl: 26,
    pill: 999,
  },
  spacing: {
    xxs: 6,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    screen: 20,
    section: 24,
  },
  typography: {
    hero: { fontSize: 32, lineHeight: 36, fontWeight: '900' },
    pageKicker: { fontSize: 10, lineHeight: 14, fontWeight: '800' },
    pageTitle: { fontSize: 32, lineHeight: 38, fontWeight: '900' },
    display: { fontSize: 32, lineHeight: 38, fontWeight: '900' },
    title: { fontSize: 20, lineHeight: 24, fontWeight: '800' },
    section: { fontSize: 22, lineHeight: 28, fontWeight: '800' },
    cardTitle: { fontSize: 15, lineHeight: 18, fontWeight: '800' },
    body: { fontSize: 12.5, lineHeight: 18, fontWeight: '500' },
    bodySmall: { fontSize: 11, lineHeight: 16, fontWeight: '500' },
    label: { fontSize: 10.5, lineHeight: 14, fontWeight: '800' },
    caption: { fontSize: 9, lineHeight: 12, fontWeight: '700' },
  },
};

export const stitchShadows = {
  card: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  float: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  soft: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
};
