import { Platform } from 'react-native';

export const stitchTheme = {
  fonts: {
    body: Platform.select({ ios: 'Avenir Next', android: 'sans-serif', default: 'System' }),
    heading: Platform.select({ ios: 'Avenir Next', android: 'sans-serif-medium', default: 'System' }),
    display: Platform.select({ ios: 'Avenir Next', android: 'sans-serif-medium', default: 'System' }),
    label: Platform.select({ ios: 'Avenir Next', android: 'sans-serif-medium', default: 'System' }),
  },
  colors: {
    background: '#f5f0e8',
    backgroundAccent: '#fdfaf4',
    backgroundElevated: '#f8f3ec',
    surface: '#fdfaf4',
    surfaceInset: '#f6efe4',
    surfaceHighlight: '#fffdf8',
    surfaceMuted: '#efe5d6',
    surfaceSubtle: '#f8f3ec',
    surfaceRaised: 'rgba(253,250,244,0.96)',
    surfaceFloating: 'rgba(253,250,244,0.92)',
    surfaceSoft: '#eef5ff',
    surfaceTint: '#d8f3e4',
    surfaceGhost: 'rgba(253,250,244,0.86)',
    navTrack: 'rgba(248,243,236,0.80)',
    navActive: '#fdfaf4',
    text: '#1a1a18',
    textMuted: '#8a9280',
    textSoft: '#4a5240',
    primary: '#1a3d2b',
    primaryContainer: '#2d6a4f',
    primaryGradientStart: '#112a1e',
    primaryGradientEnd: '#2d6a4f',
    primarySoft: '#b7e4c7',
    primaryDim: '#52b788',
    accentBlue: '#2f63ea',
    accentBlueSoft: '#d0eaff',
    accentRed: '#b7101d',
    accentPeach: '#fde8c8',
    accentBrown: '#c97d2e',
    border: 'rgba(26,61,43,0.08)',
    line: 'rgba(26,61,43,0.08)',
    borderStrong: 'rgba(26,61,43,0.16)',
    chip: '#f0e7da',
    chipActive: '#d8f3e4',
    successSurface: '#d8f3e4',
    warningSurface: '#fde8c8',
    dangerSurface: '#f7e3e4',
    shadow: 'rgba(26,61,43,0.08)',
    shadowStrong: 'rgba(26,61,43,0.14)',
    forestDeep: '#112a1e',
    mintLight: '#d8f3e4',
    sand: '#e4d9c5',
    warmWhite: '#fdfaf4',
  },
  radius: {
    xs: 10,
    sm: 14,
    md: 16,
    card: 20,
    lg: 22,
    xl: 26,
    pill: 999,
  },
  spacing: {
    xxs: 6,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    screen: 20,
    section: 24,
  },
  typography: {
    pageKicker: { fontSize: 11, lineHeight: 15, fontWeight: '800' },
    pageTitle: { fontSize: 28, lineHeight: 34, fontWeight: '900' },
    hero: { fontSize: 32, lineHeight: 38, fontWeight: '900' },
    display: { fontSize: 32, lineHeight: 38, fontWeight: '900' },
    title: { fontSize: 22, lineHeight: 27, fontWeight: '800' },
    section: { fontSize: 20, lineHeight: 25, fontWeight: '800' },
    cardTitle: { fontSize: 18, lineHeight: 23, fontWeight: '800' },
    cardMeta: { fontSize: 12, lineHeight: 16, fontWeight: '700' },
    cardDescription: { fontSize: 14, lineHeight: 20, fontWeight: '500' },
    eyebrow: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
    metricValue: { fontSize: 18, fontWeight: '900', letterSpacing: -0.3 },
    body: { fontSize: 17, lineHeight: 25, fontWeight: '500' },
    bodySmall: { fontSize: 13, lineHeight: 19, fontWeight: '500' },
    label: { fontSize: 12, lineHeight: 15, fontWeight: '800' },
    caption: { fontSize: 11, lineHeight: 15, fontWeight: '700' },
  },
};

export const stitchShadows = {
  card: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  float: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  soft: {
    shadowColor: '#1a3d2b',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
};

export const stitchStyles = {
  collectionCard: {
    backgroundColor: stitchTheme.colors.surfaceHighlight,
    borderRadius: stitchTheme.radius.card,
    padding: 14,
    paddingLeft: 18,
    marginBottom: stitchTheme.spacing.sm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    ...stitchShadows.card,
  },
  metricCard: {
    backgroundColor: stitchTheme.colors.surfaceHighlight,
    flex: 1,
    borderRadius: stitchTheme.radius.card,
    padding: stitchTheme.spacing.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    ...stitchShadows.card,
  },
  cardAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
};

